### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by wandelsonlb** [fabfuel/ecs-deploy#103]
Creating new task definition revision
Successfully created revision: 22

Updating service
Successfully changed task definition to: TD-WEBAPP-DEV:22

Deploying new task definition..................................................................................................................................................................................................................................
Deployment failed due to timeout. Please see: https://github.com/fabfuel/ecs-deploy#timeout

**Comment by fabfuel** [comment]
Please see: https://github.com/fabfuel/ecs-deploy#timeout
