### ISSUE TITLE
How can I wait for running task to stop?

### ISSUE THREAD

**Issue by grezar** [fabfuel/ecs-deploy#105]
Hi there.
I want to wait for a running task to stop  after running one-shot task using `aws ecs wait tasks-stopped`. 
To do so, I have to pass the task ARN to awscli but the ecs-deploy doesn't output task ARN.
I think it's useful if the ecs-deploy outputs ARN of the task which is run by itself.

**Comment by Maks3w** [comment]
https://github.com/fabfuel/ecs-deploy/pull/84

**Comment by grezar** [comment]
Thank you
