### ISSUE TITLE
linuxParameters not being copied in task def creation

### ISSUE THREAD

**Issue by theogravity** [fabfuel/ecs-deploy#107]
Thanks for this amazing tool!

We recently started using the tmpfs mount support in ECS, and our ops team noted that the task property `linuxParameters` (which is used to specify the mount) is not being copied over.

the format looks like this:

```
"linuxParameters": {
        "capabilities": null,
        "sharedMemorySize": null,
        "tmpfs": [
          {
            "mountOptions": [
              "rw"
            ],
            "containerPath": "/test/path",
            "size": 1
          }
        ],
        "devices": null,
        "initProcessEnabled": null
      },
```

Is there an option where we can specify additional properties to copy over?

**Comment by theogravity** [comment]
It looks like the changes required are similar to 

https://github.com/fabfuel/ecs-deploy/issues/25

I'll see if I can do a PR based on it

**Comment by theogravity** [comment]
Just realized we're using `ecs-deploy@1.4.3` - will update to latest to see if that fixes it

**Comment by theogravity** [comment]
Looks like updating to latest fixed it. Sorry about the trouble.

**Comment by fabfuel** [comment]
Thanks for the update!
