### ISSUE TITLE
Skip the task def creation when --task is provided

### ISSUE THREAD

**Issue by rprieto** [fabfuel/ecs-deploy#109]
Hi,

Thanks for this great project. We use it to simplify rolling deployments, specifying the target task definitions with `--task`.  The docs say we can pass an ARN, or a family in which case it will use the latest revision.

```bash
ecs deploy "my-cluster" "my-service" --task "arn:aws:ecs:eu-west-1:00000000:task-definition/my-service:249" --region "eu-west-1"
```

In the logs, I can see *ecs-deploy* still creates a new revision:

```
Deploying based on task definition: my-service:249
Creating new task definition revision
Successfully created revision: 250
```

Can you please explain if that's expected? Could it be skipped if specifying `--task`?
Thanks

**Comment by fabfuel** [comment]
Hi @rprieto,

yes, this is the expected and desired behaviour. A deployment with ecs-deploy works based on the creation of a new revision and optionally modifying it in the requested way (e.g. new tag, env vars, etc.).

The reason for this behaviour is, that - back then - the creation a new revision was the only (and is till the cleanest) way to enforce the ECS agent to pull the newest version of a tag and enforce a full re-deployment of the containers. 
When e.g. deploying a test environment based on Git branches and reusing the same Docker tag, this was an issue. The deployment succeeded, but the Docker images might not have been pulled/updated and the app was still running old code.

By now AWS added additional features, e.g. the option to force a new deployment when updating a service and an option for the ECS Agent to configure the pull behaviour.
But this is not considered in `ecs-deploy` at the moment.

Best
Fabian
