### ISSUE TITLE
Ability to not fail deployment if 'unable to place a task because no container instance met all of its requirements'

### ISSUE THREAD

**Issue by peritus** [fabfuel/ecs-deploy#11]
Okay, I want to use ecs-deploy in a rolling release setup. I run 3 container instances and this particular service is load balanced across 2 tasks.

When running `ecs deploy`, the command fails on my command line with 'Deployment failed' because of an error similar to this:

```
{
  '2016-12-28T14:26:44.793000+01:00': 'ERROR: (service more-services4-MyService-130NUIEVKWEKO) was unable to place a task because no container instance met all of its requirements. The closest matching (container-instance b33c7bbd-365a-4789-ad8f-2c4316e28965) is already using a port required by your task. For more information, see the Troubleshooting section of the Amazon ECS Developer Guide.'
}
```

however, 5 minutes later, the new TaskDefinition is active, steady, healthy and serving because AWS is doing a rolling release (deploy new task to 1 machine, switch the ELB to that, switch off one of the old tasks, deploy the second new task, ...)

Bottom line is: I'd like to ignore this error, as in my setup it's only a intermediate error.

So, I patched my local version like this:

```diff
diff --git a/ecs_deploy/cli.py b/ecs_deploy/cli.py
index 23dbc54..8d99017 100644
--- a/ecs_deploy/cli.py
+++ b/ecs_deploy/cli.py
@@ -157,11 +157,20 @@ def wait_for_finish(action, timeout, title, success_message, failure_message):
     waiting_timeout = datetime.now() + timedelta(seconds=timeout)
     while waiting and datetime.now() < waiting_timeout:
         sleep(1)
-        click.secho('.', nl=False)
         service = action.get_service()
-        waiting = not action.is_deployed(service) and not service.errors

-    if waiting or service.errors:
+        service_errors = dict(service.errors.items())
+
+        for error_key, error_message in dict(service_errors.items()).items():
+            if 'is already using a port required by your task' in error_message:
+                click.secho('o', nl=False)
+                del service_errors[error_key]
+
+        click.secho('.', nl=False)
+
+        waiting = not action.is_deployed(service) and not service_errors
+
+    if waiting or service_errors:
         print_errors(service, waiting, failure_message)
         exit(1)
```

Admittedly, this is not the most beautiful code because I wanted to ask for a heads up whether that would be something you'd want to integrate in `ecs-deploy` at all.

If so, should it be configurable ?

**Comment by fabfuel** [comment]
Hi @peritus and thanks for the patch.
Yes, this is a common issue and it's worth to add a workaround for it. It's a pity that boto does not provide clean error codes, so we indeed have to identify this error by string comparison.

This should be configurable via a command line parameter and I think by default the error should not be ignored.

I'm just thinking if it wouldn't be better to not ignore the error, but printing it as a warning while **continuing** the wait loop. That means, as long as the deployment succeeds within the provided `timeout` everything is fine. Then this error is just a temporary warning, but not a deployment error/failure.

What do you think?

Best
Fabian

**Comment by Intregrisist** [comment]
I am running into the same issue, that warning sounds fair to me.

**Comment by etsuo** [comment]
These sorts of failures make it really hard to use ECS for CI/CD. My deployments report as failing, but when I end up looking at the actual deployment, it's up an running. Result: developers stop trusting our CI/CD system and process gets ignored because of noisy false reporting...

**Comment by peritus** [comment]
@etsuo 

I switched to 4 instances since (with single services only being load balanced on 2 of them at a time) -> the warning can't happen anymore with our setup.

Want to switch to Amazon's Application Load Balancer soon (currently still on ELB) where the warning should also not occur.

**Comment by fabfuel** [comment]
@etsuo: The warning is a strong indication, that your cluster is undersized or the deployment options are not ideal. If your cluster does not have enough capacity to handle parallel blue-green-deployments, you can easily avoid the warning by reducing the deployment option "Maximum percent" too `100`.

Nevertheless I see a strong need to implement this improvement and I will do that as soon as I find some time. 

Best
Fabian

**Comment by fabfuel** [comment]
Version 1.2.0 has been released on PyPI
https://pypi.python.org/pypi/ecs-deploy/1.2.0

**Comment by jobiwankanobi** [comment]
Check out second answer for how to replace running task (disable blue/green deployment): https://stackoverflow.com/questions/46018883/best-practice-for-updating-aws-ecs-service-tasks
