### ISSUE TITLE
dependsOn not getting into new task definitions

### ISSUE THREAD

**Issue by james-m** [fabfuel/ecs-deploy#125]
Hi,

We've just started using ecs-deploy as a tool in a GH Action to deploy newly built container images to an ECS Fargate cluster. This cluster is stood up with AWS CDK which is where we're creating the initial TaskDefinition with CDK Constructs. This works great and we do not want to have a taskdef.json file or similar kind of configuration. 

We're further using datadog to monitor our containers, which means we have our runtime container with our app and the DD container next it as a sidecar. The recommended deployment of the DD container is to make it `dependsOn` the runtime container to have started. We do this with CDK and it works great, but when we deploy new version of built container images with ecs-deploy the new task defs do _not_ seem to have the dependsOn config. 

So taskdef :1 has this in the DD container:

```
...
     "image": "datadog/agent:latest",
      "startTimeout": null,
      "firelensConfiguration": null,
      "dependsOn": [
        {
          "containerName": "<<runtimeContainerName>>",
          "condition": "START"
        }
      ],
      "disableNetworking": null,
      "interactive": null,
      "healthCheck": null,
      "essential": false,
...
```

But later version have it as null:
```
...
      "image": "datadog/agent:latest",
      "startTimeout": null,
      "firelensConfiguration": null,
      "dependsOn": null,
      "disableNetworking": null,
      "interactive": null,
...
```

This is particularly problematic with DD monitoring because (for reasons not completely known to me) if the DD container comes up first to takes the port that our runtime container needs to join our LB and things do not work. 

I know `dpendsOn` is a relatively recent ECS thing, was wondering if this is intended or if there is another config I can set in the ECS invocation to make this work? 

Our ecs-deploy call looks like this, doing the "multi-image" kind through docker:
```
docker run --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY --env AWS_REGION \
    --env ECR_REGISTRY --env ECR_REPOSITORY_APP \
    fabfuel/ecs-deploy:1.7.1 ecs deploy cluster-name service-name \
    --region $AWS_REGION --access-key-id $AWS_ACCESS_KEY_ID --secret-access-key $AWS_SECRET_ACCESS_KEY \
    --image dev-app-task-container $ECR_REGISTRY/$ECR_REPOSITORY_APP:$IMAGE_TAG \
    --image datadog-task-container datadog/agent:latest
```

Thanks for a great tool and any help / guidance you can give!

**Comment by fabfuel** [comment]
Hi @james-m,

thanks for the detailed issue report! You're welcome, glad that my tool is helpful to others, too!

Just a quick idea, I did not look into this yet in detail:
It sounds a bit like this could be related to new parameters, which are not covered by the underlying boto3/botocore libraries yet.

I have just triggered a new Docker build for the `develop` tag. Could you please your call with tag `develop` instead of `1.7.1`?

Thanks
Fabian

**Comment by gbooth27** [comment]
@fabfuel Working on this with @james-m and just tried using the `develop` tag and that seems to have done the trick in preserving the container dependency ordering when updating the task with your new tool. thanks! can you let us know when the current `develop` container becomes an official release?

**Comment by fabfuel** [comment]
Hi @gbooth27, please try version/tag `1.10.0`, maybe this is already "new enough".
If it does not, I will create a small release which only contains the updated external boto libraries.

Best
Fabian

**Comment by gbooth27** [comment]
ok looks like `1.10.0` is new enough. thanks for the help!
