### ISSUE TITLE
Error Signature expired

### ISSUE THREAD

**Issue by lmnzr** [fabfuel/ecs-deploy#126]
I try to use docker to deploy service in cluster. Then I get the following error,

An error occurred (InvalidSignatureException) when calling the DescribeServices operation: Signature expired: 20191209T104625Z is now earlier than 20191210T033904Z (20191210T034404Z - 5 min.)

Is there any solution for this ?

**Comment by fabfuel** [comment]
Hi @lmnzr, this error was not directly related to ecs-deploy or ECS, it was an issue in EC2, please follow up for example here: https://forums.aws.amazon.com/thread.jspa?messageID=819826&tstart=0

Best
Fabian
