### ISSUE TITLE
New task definitions do not include AWS tags from previous ones

### ISSUE THREAD

**Issue by twelvelabs** [fabfuel/ecs-deploy#130]
I recently switched to ecs-deploy from the [fargate](https://github.com/turnerlabs/fargate) CLI. I  just noticed that after the change my task definitions are no longer tagged (the fargate CLI maintained them across deploys). 

Looking through the source, it looks like you don't pass `include=['TAGS']` when getting the task definition to copy. Unfortunately, the AWS api [doesn't return the tags attribute unless you explicitly ask for it](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html#ECS.Client.describe_task_definition)... which is super annoying 🙄. 

@fabfuel Would you be open to a PR that added the `include` kwarg?

**Comment by fabfuel** [comment]
Hi @twelvelabs,
yes, your PR would be highly appreciated!
Thanks
