### ISSUE TITLE
Deploy timeouts 

### ISSUE THREAD

**Issue by MrPink** [fabfuel/ecs-deploy#15]
I'm getting timeouts when trying to deploy to a cluster, I'm using

`ecs deploy <cluster> <service> -i <service> repo/foo:bar`

I'm running the following 

`NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1298.7.0
VERSION_ID=1298.7.0
BUILD_ID=2017-03-31-0215
PRETTY_NAME="Container Linux by CoreOS 1298.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"`

I'm using the latest image from Docker hub for the `ecs-agent`, it basically deploys fine but doesn't remove the old task so the deploy never finishes. Everything in the ECS agent log looks fine to me, any pointers?

**Comment by MrPink** [comment]
I'm using `Name: ecs-deploy Version: 1.1.0` btw

**Comment by fabfuel** [comment]
Hi @MrPink,

the timeout error basically means, that ECS takes longer for the full deployment process then `ecs-deploy` is told to wait. You can increase the time (in seconds) to wait for finishing the deployment via the `--timeout` parameter.

There are several reasons why a deployment can take a long time. Please have a look at this: https://github.com/fabfuel/ecs-deploy/issues/14#issuecomment-277424439

Best
Fabian
