### ISSUE TITLE
Pinned click dependency

### ISSUE THREAD

**Issue by si14** [fabfuel/ecs-deploy#168]
Hey there!

Click is currently pinned to `<7.0.0`, which conflicts with tools like `black` (requires `click>=7.1.2`) or `piptools` (requires `click>=7`). Do you think it's feasible to update it?

Thanks for a great tool.

**Comment by fabfuel** [comment]
Hi Dmitry,

I changed that just a few days ago in the `develop` branch. The next release will be using Click 7.1.2 and not be pinning to <7.0.0 anymore. 

You are welcome - happy to hear, that the tool is helpful for you!

Best
Fabian

**Comment by si14** [comment]
Thanks!
