### ISSUE TITLE
ecs deploy timeout

### ISSUE THREAD

**Issue by smilelikeshit** [fabfuel/ecs-deploy#186]
hi im always return this error 

Deployment failed due to timeout. Please see: https://github.com/fabfuel/ecs-deploy#timeout

im already set timeout 30,60,120,300 and last 600 . still return error. what should i do  ?

thanks

**Comment by fabfuel** [comment]
Hi,

please check the ECS console for the specific error(s) happening during your deployment. ecs-deploy only triggers ECS and shows, that the deployment has failed. Most likely this is due to configuration or issues in your images.

Best
Fabian

**Comment by smilelikeshit** [comment]
thanks @fabfuel  im use fargate for deployment. and increase timeout to 1200 and solved. this problem from AWS need much time for blue/green.
