### ISSUE TITLE
Incorrect line wrap in Chrome and Firefox in deploy_task_definition

### ISSUE THREAD

**Issue by F1ashhimself** [fabfuel/ecs-deploy#191]
It looks like Chrome (97.0.4692.71) and Firefox have incorrect line wrapping for such lines like on screenshot and it tries to wrap line right before last symbol. And it is reproducible with different window resolutions.
<img width="648" alt="Screenshot 2022-01-11 at 19 00 30" src="https://user-images.githubusercontent.com/3996366/149138066-185ef382-6c38-4f87-b8e2-f8dff3181fab.png">
But in Safari all looks good.

It can be avoided if we will add space or new line between words and dots here https://github.com/fabfuel/ecs-deploy/blob/af252d2035a5542a0581f408b55a0976c784da0c/ecs_deploy/cli.py#L494 like
```python
click.secho(f'{title} ', nl=False)
```

**Comment by fabfuel** [comment]
Hi Max, thats an interesting issue! 🙂  
May I ask what tool you're using in the browser which causes this?

Best
Fabian

**Comment by F1ashhimself** [comment]
@fabfuel sorry for late answer, I think this is our company internal tool for deployment. But there are no special css for wrapping this.

**Comment by fabfuel** [comment]
No problem. I already added a line break before the "waiting dots" (https://github.com/fabfuel/ecs-deploy/commit/289c51b0521999d21a946d0d81b12c38e440e6a2). It's in the `develop` branch and will be part of the next release. 

Best
Fabian

**Comment by F1ashhimself** [comment]
Thank you very much.
