### ISSUE TITLE
1.12.0 missing in dockerhub

### ISSUE THREAD

**Issue by marekmoscichowski** [fabfuel/ecs-deploy#201]
Hi!

Would it be possible to push the latest release 1.12.0 into dockerhub registry?

Thank you!

**Comment by fabfuel** [comment]
Hi Marek,

Docker Hub does not run builds anymore unless you pay for it.
I have to and will migrate the Docker image building to GitHub Actions, let's keep this issue open for tracking that.

Best
Fabian

**Comment by fabfuel** [comment]
Version 1.13.0 is now available on Docker Hub
https://hub.docker.com/layers/ecs-deploy/fabfuel/ecs-deploy/1.13.0/images/sha256-b53d81f62cd1743d6fb466536a0ce6ea46307e684298835d8d74f844664df6be?context=repo

Best
Fabian
