### ISSUE TITLE
Kill running tasks when deploying new task definition

### ISSUE THREAD

**Issue by Dvelezs94** [fabfuel/ecs-deploy#21]
Right now when you deploy a new task definition on an existing service, if you don't have enough capacity on the cluster to place the new task, the script will just exit with this message
"ERROR: (service foo) was unable to place a task because no container instance met all of its requirements. The closest matching (container-instance instance-id-bar) has insufficient CPU units available. For more information, see the Troubleshooting section of the Amazon ECS Developer Guide"
This happens even if you set the "Minimum healthy percent" to 0, so the container will eventually be deployed, but you don't know when.
In this case I think it would be a good idea to have a new flag to kill the existing tasks right after the service has been updated, that way the new one will be placed without any issues

NOTE: this happens very often on dev/qa environments, where you don't want to assign too much resources to the clusters.

**Comment by fabfuel** [comment]
Hi @Dvelezs94,

I would like keep the task scheduling to the ECS agent and keep focusing on managing ECS services only.

But I just added a new parameter called `--ignore-warnings`. With this set, the script ignores these kind of capacity warnings and continues waiting for a successful finish. See PR #18  
I will create new release version soon.

Only changing "Minimum healthy percent" to `0` has no effect on that issue, in addition you would have to change "Maximum healthy percent" to `100` to prevent the warning/error.

Please have a look at the original issue as well: #11 
> The warning is a strong indication, that your cluster is undersized or the deployment options are not ideal. If your cluster does not have enough capacity to handle parallel blue-green-deployments, you can easily avoid the warning by reducing the deployment option "Maximum percent" too 100.

Best
Fabian

**Comment by Dvelezs94** [comment]
that flag should work too! Thanks @fabfuel

**Comment by fabfuel** [comment]
Fixed in #18

**Comment by fabfuel** [comment]
Version 1.2.0 has been released on PyPI
https://pypi.python.org/pypi/ecs-deploy/1.2.0
