### ISSUE TITLE
Broadside is a tool to do many of the same things this does and considerably more

### ISSUE THREAD

**Issue by apurvis** [fabfuel/ecs-deploy#22]
Just FYI:
https://github.com/lumoslabs/broadside

[original blog post when we did the first release](http://engineering.lumosity.com/amazon%20web%20services/amazon%20elastic%20compute%20cloud/amazon%20ec2%20container%20service/deploys/docker/containers/2017/01/23/broadside-is-a-tool-for-managing-ec2-containers-in-amazon-web-services/)

**Comment by fabfuel** [comment]
How can we resolve this "issue", @apurvis? 😉 
Do you want to set up cross links?

**Comment by apurvis** [comment]
could do that, sure.  open a PR with me as a reviewer and i'll copy it over in the Broadside docs

**Comment by fabfuel** [comment]
You're welcome to do the same

**Comment by apurvis** [comment]
i don't see a PR?
