### ISSUE TITLE
New release that supports Python 3.12

### ISSUE THREAD

**Issue by alasdairnicol** [fabfuel/ecs-deploy#224]
Thank you for your work on ecs-deploy

Do you have any plans to make a new release? It would be great to have a new release that includes the fixes in #219 to support Python 3.12.

**Comment by pietrodn** [comment]
I second this request. 😄 
For now, a workaround is to install from Git:

```sh
pipx install git+https://github.com/fabfuel/ecs-deploy.git
```

**Comment by fabfuel** [comment]
Hi everyone, 

sorry for the delay.
I have just released version `1.15.0` which drops Python2 support and adds Python 3.12.

Best
Fabian
