### ISSUE TITLE
New task definitions lose networkMode and placementConstraint attributes

### ISSUE THREAD

**Issue by woodlee** [fabfuel/ecs-deploy#25]
The [network mode](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#network_mode) and [task placement constraint](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#constraints) parameters of task definitions are relatively recent additions. It looks like this tool isn't set up to handle them presently. When I run an `ecs deploy` the new task definition loses the `networkMode: host` I originally had on the prior task definition.

A quick fix would probably be to just update `register_task_definition` and `update_task_definition` in `ecs.py` to add the new attributes. A longer-term one might be to rearrange things so that the new definition is a complete copy of the old (i.e. no matter what new attributes get added in the future), with targeted mutations of only what's necessary to effect the deployment.

**Comment by fabfuel** [comment]
Hi @woodlee, you're right, currently these new ECS features have to be added explicitly. I will create a fix, that makes `ecs-deploy` compatible to new task definition attributes in the future as well.
