### ISSUE TITLE
Do not print all existing environment variables & values when changing environment

### ISSUE THREAD

**Issue by mofesola** [fabfuel/ecs-deploy#26]
`Changed environment of container 'container_name' to: {whatever}` User should be able to choose whether or not to echo the previous and new variables to current shell or not.

**Comment by fabfuel** [comment]
Hi @mofesola, what's the use case behind that? 
Do you want to prevent exposing all existing environment variables?

**Comment by mofesola** [comment]
Yeah, so I just had my sensitive environment variables echoed back in my build pipeline was: {Password, Secret Key ...} etc.

It will be an important feature to turn echoing of environment variables off

**Comment by fabfuel** [comment]
Yes, I agree. What about only showing the env variables wich changed during the deployment? These are visible in the command anyway, but nothing else would be exposed.

**Comment by mofesola** [comment]
It will be fine to have that. I'll like to know which variables were updated, but not the update values.]
Plus, won't it be a nice to have if strings can be compared before declaring them updated? So for example, if the previous value of a variable was `'housemanship'` and it is still being updated with `'housemanship'` then the variable name shouldn't be echoed back as being updated.

Just a thought

**Comment by fabfuel** [comment]
Yes, value comparison makes sense. So the log should show, what env variables actually changed or were added.

**Comment by mofesola** [comment]
Yes. Thank you.
