### ISSUE TITLE
Single task for staging, update with new image

### ISSUE THREAD

**Issue by bee-keeper** [fabfuel/ecs-deploy#27]
Hi there,

Thanks for the tool, I quickly used the incredibly handy `ecs deploy my-cluster my-service --tag 1.2.3` to update 2 containers running behind an ELB.  Besides the fact it takes around 6 minutes (seems this is to do with AWS though?!) all worked fine.

My question is:  can i use this cli to update a single container (no load balancing) with downtime? 
 For staging I simply want to bring down the old task and bring up a new one.  If I try this using `ecs deploy my-cluster my-service --tag 1.2.3` I see ECS complains due to the lack of dynamic port mapping.  Ie both tasks use same port rather than the old task is brought down and the new task is brought up.  I have tried even when setting healthy to 0 but it seems the same issue occurs.

Any thoughts, ideas appreciated.  Thanks,

**Comment by fabfuel** [comment]
Hi @bee-keeper,

yes, the duration of your deployment is only depending on the deployment process on AWS. `ecs-deploy` just creates a new task definition and deployment configuration.

For more details on deployment duration, please have a look here: https://github.com/fabfuel/ecs-deploy/issues/14#issuecomment-277424439

Yes, what you describe is possible. To achieve that, you have to set the deployment options in the service to these values:
- Minimum healthy percent: 0
- Maximum percent: 100

The important value here is `Maximum percent: 100`. This means, that the service will never run 2 containers at the same time, which should avoid the warning, which you described above.

Best
Fabian

**Comment by bee-keeper** [comment]
Thanks for the quick reply.  I'll give it a go.
