### ISSUE TITLE
Deploying task definition -(Timeout)

### ISSUE THREAD

**Issue by Thussubasa** [fabfuel/ecs-deploy#36]
When trying to define a new task I come across the following message:

Deployment failed (timeout)

I'm runing v1.2.0.

**Comment by fabfuel** [comment]
Hi @Thussubasa,

the timeout error only means, that AWS ECS takes longer for the full deployment cycle then ecs-deploy is told to wait. You can increase the time (in seconds) to wait for finishing the deployment via the `--timeout` parameter.

There are several reasons why a deployment can take a long time.
Please have a look here: https://github.com/fabfuel/ecs-deploy/issues/14#issuecomment-277424439

Best
Fabian

**Comment by fabfuel** [comment]
I have added this to the new Troubleshooting section in the readme
https://github.com/fabfuel/ecs-deploy#timeout
