### ISSUE TITLE
deregister option

### ISSUE THREAD

**Issue by nocode99** [fabfuel/ecs-deploy#37]
I installed ecs deploy via pip and from source, but it seems I still don't have the deregister option.  Is there any timeline when this option will be available?

**Comment by fabfuel** [comment]
Hi @nocode99, the option is already available in the `develop` branch.
I will create a new release soon!

Best
Fabian

**Comment by fabfuel** [comment]
Hi @nocode99, I just released version 1.4.0 which includes the `--no-deregister` option:
https://github.com/fabfuel/ecs-deploy/releases/tag/1.4.0

Best
Fabian
