### ISSUE TITLE
ImportError: No module named boto3.session

### ISSUE THREAD

**Issue by haimari** [fabfuel/ecs-deploy#41]
$ pip install boto3 ecs-deploy
Collecting boto3
  Downloading boto3-1.4.7-py2.py3-none-any.whl (128kB)
Collecting ecs-deploy
  Downloading ecs-deploy-1.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vWl8tn/ecs-deploy/setup.py", line 6, in <module>
        from ecs_deploy.ecs import VERSION
      File "ecs_deploy/ecs.py", line 3, in <module>
        from boto3.session import Session
    ImportError: No module named boto3.session

**Comment by haimari** [comment]
This worked OK before, until your last commit today.

**Comment by haimari** [comment]
Works again... same commands , same env

**Comment by fabfuel** [comment]
I just pushed the fix. Version 1.4.1 will be on PyPI soon

**Comment by fabfuel** [comment]
1.4.1 is now available on PyPI. Sorry & thanks for reporting!
