### ISSUE TITLE
Enable rollback feature

### ISSUE THREAD

**Issue by Dvelezs94** [fabfuel/ecs-deploy#44]
Hello, I was thinking it would be nice to add a rollback feature. This means that it will deregister the previous task definition after the deploy is marked a healthy, otherwise it will rollback to the previous one after the TIMEOUT

**Comment by fabfuel** [comment]
Hi @Dvelezs94 

this feature was actually released a few days ago:
https://github.com/fabfuel/ecs-deploy/releases/tag/1.4.0

If you deploy with `--rollback`, you achieve exactly what you described.

Best
Fabian
