### ISSUE TITLE
ImportError: No module named tz

### ISSUE THREAD

**Issue by foragerr** [fabfuel/ecs-deploy#46]
```
Traceback (most recent call last):
  File "/usr/local/bin/ecs", line 7, in <module>
    from ecs_deploy.cli import ecs
  File "/usr/local/lib/python2.7/site-packages/ecs_deploy/cli.py", line 11, in <module>
    from ecs_deploy.ecs import DeployAction, ScaleAction, RunAction, EcsClient, \
  File "/usr/local/lib/python2.7/site-packages/ecs_deploy/ecs.py", line 5, in <module>
    from dateutil.tz.tz import tzlocal
ImportError: No module named tz
```

https://github.com/fabfuel/ecs-deploy/blob/master/ecs_deploy/ecs.py#L5

    - from dateutil.tz.tz import tzlocal
    + from dateutil.tz import tzlocal

**Comment by fabfuel** [comment]
Hi @foragerr, how can I reproduce this?

**Comment by foragerr** [comment]
My command was a pretty generic ecs deploy command with three `-e` env vars 

    ecs deploy cluster service --region us-west-2  \
    -e service key1 value1 \
    -e service key2 value2 \
    -e service key3 value3

also:

      $ python
      Python 2.7.12 (default, Nov 19 2016, 06:48:10)
      [GCC 5.4.0 20160609] on linux2
      Type "help", "copyright", "credits" or "license" for more information.
      >>> from dateutil.tz.tz import tzlocal
      Traceback (most recent call last):
        File "<stdin>", line 1, in <module>
      ImportError: No module named dateutil.tz.tz

maybe this is a issue with a specific dateutil version?

**Comment by foragerr** [comment]
works fine with python dateutil 2.6.1

**Comment by fabfuel** [comment]
Alright, thanks for the update!
