### ISSUE TITLE
Add service status check

### ISSUE THREAD

**Issue by fatgit** [fabfuel/ecs-deploy#5]
Hello, 
Could you add a check on Service stable?
Now I can deploy a new task definition but something will go wrong and the new task definition will not accept and I will not know this. 
http://boto3.readthedocs.io/en/latest/reference/services/ecs.html#ECS.Waiter.ServicesStable

**Comment by fabfuel** [comment]
Good hint, I will have a look at it.

I already check for errors during the deployment. At the moment, the deployment is considered successful, if the desired count is equal to the number of tasks running the newly created task definition. Currently you get a timeout (error), if e.g. you specified an image which does not exist and the new task definition could not be deployed. 

What kind of "something will go wrong" do you have in mind? And how would this check improve that? 

Best
Fabian

**Comment by fatgit** [comment]
Look. I did test. I deliberately broke my app and stared to deploy by your ecs-deploy.  My task run and your application said "Deployment successful" but then my app was down by reason 
`service frontend (instance i-12121211) is unhealthy in elb frontend-sb-v2 due to (reason Instance has failed at least the UnhealthyThreshold number of health checks consecutively.)`
If you use class _ECS.Waiter.ServicesStable_ from boto3 you will be able to control service status. And your application will wait when Services will be stable or exit with error after 10 min.

**Comment by fabfuel** [comment]
Yes, true. Currently I consider a running task as success, but it makes sense to wait for the ELB health checks.

**Comment by fatgit** [comment]
Yes, because a developer is thinking "Cool, I have deployed new task! " while the old task is working. And will be cool, if I are able to decide to delete or keep the old version task definition. May be I will want to do rollback my task.

**Comment by StyleT** [comment]
@fabfuel Hi! Do you have any plans to resolve this issue in the next few days? If not I can help you with this... Issue here that I'm not familiar with Python, but it shouldn't be a big problem :) Library looks quite simple.

**Comment by fabfuel** [comment]
I just checked the implementation of the boto waiter. 

Actually it's also comparing the number of running tasks with the desired count, but in addition the number of deployments, which has to be `1`. Have a look:
https://github.com/boto/botocore/blob/develop/botocore/data/ecs/2014-11-13/waiters-2.json#L69

I will add a check for the number of deployments in a second. Then it will be equally accurate.

**Comment by StyleT** [comment]
@fabfuel Yeah, I just discovered the same. Maybe I would be better to use boto3 Waiter instead of custom code?

**Comment by fabfuel** [comment]
What ever suits you. This tool is based on boto3, it's just simplifying some inconvenient tasks. Fix version 0.3.2 will be available later today
