### ISSUE TITLE
Updating ECS scheduled tasks

### ISSUE THREAD

**Issue by andrewmichaelsmith** [fabfuel/ecs-deploy#54]
(First off - thanks for the helpful tool that saved me a load of time).

We use scheduled tasks on ECS and think it would be useful if we could update scheduled tasks with this tool. When we push a new docker image we'd like to also use your tool to update these.

I believe using the current aws cli you would do:

```
aws ecs register-task-definition # task def with new image
aws events put-targets # point existing rule at new task def
```

It kind of breaks your current CLI, so we'd have to think about that.

Is this something you would consider a PR for?

**Comment by mohsinhijazee** [comment]
I am interested in how you are running these scheduled tasks. What I found out is that it is based on CloudWatch Alarms and those alarms have a limit of some number of alarms per account per region so you cannot indefinitely create per alarm per scheduled tasks.

What I am doing is - reusing the alarms while adding targets to them. Interestingly enough, there is also a limit of 100 targets per alarm if I am not wrong.

I can share the terraform description of my setup and that can be a basis of this feature.

Thoughts?

**Comment by andy-plutoflume** [comment]
This was fixed by https://github.com/fabfuel/ecs-deploy/pull/58

**Comment by nwsparks** [comment]
@andy-plutoflume that PR appears to still be open and not merged so this issue is still present.

**Comment by grgizem** [comment]
hey @fabfuel this PR is merged, you can close this issue

**Comment by fabfuel** [comment]
Thanks for the heads-up @grgizem!
