### ISSUE TITLE
ecs deploy doesn't stop old revision running tasks

### ISSUE THREAD

**Issue by omermizrahi** [fabfuel/ecs-deploy#56]
Hi, i'm using ecs deploy with gitlab-ci, when trying to use it on service with 2 running tasks, it won't stop the tasks, and get timeout on the deployment.

the command im using:
```ecs deploy --region ${ECS_REGION} ${CLUSTER_NAME} ${SERVICE_NAME} --deregister --task ${TASK_FAMILY} --user gitlab-ci```

the new revision is deployed, and running 2 tasks, but the old tasks doesn't stop.
After the timeout below ends, i got 1 task with revision 24, and 2 tasks with revision 25. 

```bash
$ ecs deploy --region ${ECS_REGION} ${CLUSTER_NAME} ${SERVICE_NAME} --deregister --task ${TASK_FAMILY}  --user gitlab-ci
Deploying based on task definition: backend-engine

Creating new task definition revision
Successfully created revision: 25

Updating service
Successfully changed task definition to: backend-engine:25

Deploying new task definition........................................................................................................................................................................................................................................................
Deployment failed due to timeout. Please see: https://github.com/fabfuel/ecs-deploy#timeout

ERROR: Job failed: exit code 1
```

**Comment by fabfuel** [comment]
Hi, did you check the link given in the output?

**Comment by omermizrahi** [comment]
Hi, thanks, im closing the issue, it was the connection draining of the containers, i increased the timeout.
