### ISSUE TITLE
Update service without making new task definition

### ISSUE THREAD

**Issue by kalemdzievski** [fabfuel/ecs-deploy#57]
Is there any way I can update the service without creating new task definition (I couldn't find anything in the documentation)? 
Since I am updating only the docker image and always using the latest tag, there is no need for new  task definition. 
Via the AWS Console this can be done by checking the force new deployment option when updating the service.

Thanks,
Nikola.

**Comment by fabfuel** [comment]
Hi Nikola,

no, it's not. The deployment is currently always based on a new task definition revision.

Just a general thought:
If possible, it's a big advantage if you can avoid using `latest` at all. At least on production, you always should deploy specific tags - that's the only way to ensure, that exactly the code is running, which you expect to be running.

We use branch-based tags (which get overwritten on every commit) on testing environments and in the past, I saw issues during the image pulling on the ECS nodes, which lead to some containers running the newest code and some running an older version. That's super ugly to debug.

Recently, AWS added a new option with which you can control how the ECS agent pulls images, which might be useful in your scenario. It's called `ECS_IMAGE_PULL_BEHAVIOR`, see https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html.

Best
Fabian

**Comment by kalemdzievski** [comment]
Fabuel,

thanks for the quick reply!. I understand the issues that you have stated.
Love your tool by the way. Keep it going!

Best,
Nikola.

**Comment by jobiwankanobi** [comment]
Wanted to update this with an answer I found from stackoverflow - for those who want a simpler use of ecs deploy without blue/green deployments. Check out the second answer on this https://stackoverflow.com/questions/46018883/best-practice-for-updating-aws-ecs-service-tasks 
Basically you unset blue/green deployments in your service definition by setting minimum healthy percent to 1 and max to 100. Then the ecs deploy command will replace the running task with the new task you are deploying. Obviously this isn't the optimal setup but for those trying to get the minimum setup working, it could be helpful.
