### ISSUE TITLE
ECS service Daemon mode

### ISSUE THREAD

**Issue by haimari** [fabfuel/ecs-deploy#59]
Hello, i set the Service in "DAEMON" mode meaning the # of desired tasks is Automatic (Top right corner at the screen-shot)

![screenshot from 2018-07-02 13-16-44](https://user-images.githubusercontent.com/11332517/42158871-727414ac-7dfa-11e8-8443-8557f4d4aad9.png)

However i'm getting an error when deploying a new tag

**Command**

`ecs deploy --region ${AWS_REGION} ${CLUSTER_NAME} ${ECS_SERVICE_NAME} --tag ${CI_COMMIT_SHA} --timeout 1200`

**Error:**

```
Creating new task definition revision
Successfully created revision: 6

Updating service
An error occurred (InvalidParameterException) when calling the UpdateService operation: The daemon scheduling strategy does not support a desired count for services. Remove the desired count value and try again

```
i must be missing something here
can you please advise on this ?

**Comment by tglastra** [comment]
@haimari Looking at the code, I can see the desired_count parameter is always used when calling boto's update_service(), regardless of wether this is applicable or not. @fabfuel How about a -type=daemon|replica flag or how about querying the type and using desired_count accordingly?

**Comment by sousousore1** [comment]
+1

**Comment by fabfuel** [comment]
Hey guys, I added support for services with scheduling strategy `DAEMON`.
Release 1.5.0 on pypi coming up!
