### ISSUE TITLE
`ecs run ...` does not work with Fargate

### ISSUE THREAD

**Issue by squaresurf** [fabfuel/ecs-deploy#61]
I get the following when I try to run `ecs run ...` with a Fargate cluster.

```
An error occurred (InvalidParameterException) when calling the RunTask operation: Network Configuration must be provided when networkMode 'awsvpc' is specified.
```

**Comment by jperelli** [comment]
Hi, are there any ideas or updates in this one?

**Comment by justinsoong** [comment]
+1

**Comment by JeppeMariagerLam** [comment]
+1

**Comment by guidiego** [comment]
Some updates?

**Comment by sopeters** [comment]
+1

**Comment by sopeters** [comment]
I've tried to add this - the Network Config is in the Service itself, so need this as an argument for `ecs run` command. Diff below:

`--- a/ecs_deploy/cli.py
+++ b/ecs_deploy/cli.py
@@ -151,6 +151,7 @@ def scale(cluster, service, desired_count, access_key_id, secret_access_key, reg

 @click.command()
 @click.argument('cluster')
+@click.argument('service')
 @click.argument('task')
 @click.argument('count', required=False, default=1)
 @click.option('-c', '--command', type=(str, str), multiple=True, help='Overwrites the command in a container: <container> <command>')
@@ -161,18 +162,19 @@ def scale(cluster, service, desired_count, access_key_id, secret_access_key, reg
 @click.option('--secret-access-key', help='AWS secret access key')
 @click.option('--profile', help='AWS configuration profile name')
 @click.option('--diff/--no-diff', default=True, help='Print what values were changed in the task definition')
-def run(cluster, task, count, command, env, secret, region, access_key_id, secret_access_key, profile, diff):
+def run(cluster, service, task, count, command, env, secret, region, access_key_id, secret_access_key, profile, diff):
     """
     Run a one-off task.

     \b
     CLUSTER is the name of your cluster (e.g. 'my-custer') within ECS.
+    SERVICE is the name of your service (e.g. 'my-app') within ECS.
     TASK is the name of your task definition (e.g. 'my-task') within ECS.
     COUNT is the number of tasks your service should run.
     """
     try:
         client = get_client(access_key_id, secret_access_key, region, profile)
-        action = RunAction(client, cluster)
+        action = RunAction(client, cluster, service)

         td = action.get_task_definition(task)
         td.set_commands(**{key: value for (key, value) in command})`

`--- a/ecs_deploy/ecs.py
+++ b/ecs_deploy/ecs.py
@@ -80,11 +80,12 @@ class EcsClient(object):
             taskDefinition=task_definition
         )

-    def run_task(self, cluster, task_definition, count, started_by, overrides):
+    def run_task(self, cluster, task_definition, count, network_configuration, started_by, overrides):
         return self.boto.run_task(
             cluster=cluster,
             taskDefinition=task_definition,
             count=count,
+            networkConfiguration=network_configuration,
             startedBy=started_by,
             overrides=overrides
         )
@@ -110,6 +111,10 @@ class EcsService(dict):
     def task_definition(self):
         return self.get(u'taskDefinition')

+    @property
+    def network_configuration(self):
+        return self.get(u'networkConfiguration')
+
     @property
     def desired_count(self):
         return self.get(u'desiredCount')
@@ -590,10 +595,11 @@ class ScaleAction(EcsAction):


 class RunAction(EcsAction):
-    def __init__(self, client, cluster_name):
-        super(RunAction, self).__init__(client, cluster_name, None)
+    def __init__(self, client, cluster_name, service_name):
+        super(RunAction, self).__init__(client, cluster_name, service_name)
         self._client = client
         self._cluster_name = cluster_name
+        self._service_name = service_name
         self.started_tasks = []

     def run(self, task_definition, count, started_by):
@@ -602,6 +608,7 @@ class RunAction(EcsAction):
                 cluster=self._cluster_name,
                 task_definition=task_definition.family_revision,
                 count=count,
+                network_configuration=self._service.network_configuration,
                 started_by=started_by,
                 overrides=dict(containerOverrides=task_definition.get_overrides())
             )`

**Comment by sopeters** [comment]
I've submitted a PR for this - please review and let me know if that's the right approach.

**Comment by fabfuel** [comment]
Hi everyone,

this issues was address in release 1.8.0 - please have a look if your task placements work correctly in your Fargate cluster now: https://github.com/fabfuel/ecs-deploy#run-a-task-in-a-fargate-cluster

Best
Fabian

**Comment by ORESoftware** [comment]
I have this configuration:

```
  "networkConfiguration": {
    "awsvpcConfiguration": {
      "assignPublicIp": "ENABLED",
      "securityGroups": [
        "sg-0a6e7d4a5238fe3c6"
      ],
      "subnets": [
        "subnet-05a6557c"
      ]
    }
  },
```

I still get this error:

```
$ aws ecs run-task --cluster tutorial --task-definition ikg-api:1  --count 1
```

> An error occurred (InvalidParameterException) when calling the RunTask operation: Network Configuration must be provided when networkMode 'awsvpc' is specified.

any help appreciated

**Comment by fabfuel** [comment]
Hi @ORESoftware, 

first of all, you are not running ecs-deploy, but the aws cli tool – different thing 😉 

You **can** run your task using my tool, but:
The configuration you mention is set in a ECS service, which is not used when you run a task on its own. When you use VPC networking, the cluster, security groups and subnets have to be defined explicitly when running the task definition. Please try this:
```
$ ecs run tutorial ikg-api:1 --securitygroup sg-0a6e7d4a5238fe3c6 --subnet subnet-05a6557c --public-ip
```

Best
Fabian

**Comment by joe-niland** [comment]
For anyone searching for a solution, the above nearly works. I needed to add `--launchtype FARGATE` to avoid the network config error
