### ISSUE TITLE
Add --profile for AWS

### ISSUE THREAD

**Issue by ChristianFranke** [fabfuel/ecs-deploy#64]
I use profiles to login to aws:
`$(aws ecr get-login --profile dev)`

Would it be possible to add an option --profile to send it to aws with ecr-deploy? 

For example:
`aws ecs describe-task-definition --task-definition web-service --profile dev`
is working.

`aws ecs describe-task-definition --task-definition web-service`
not (An error occurred (ClientException) when calling the DescribeTaskDefinition operation: Unable to describe task definition.).

**Comment by fabfuel** [comment]
Hi @ChristianFranke,

this option already exists, please see
```
ecs deploy --help
```

The option is:
```
  --profile TEXT                  AWS configuration profile name
```

Best
Fabian
