### ISSUE TITLE
"deployment failed" but tasks are updated

### ISSUE THREAD

**Issue by jamesdixon** [fabfuel/ecs-deploy#65]
Hi,

First, thanks for this tool. It's been great thus far.

I'm seeing a "Deployment failed" message, but my tasks are updated appropriately. Is there a way to get more information as to what is actually failing?

```
Creating new task definition revision
Successfully created revision: 18

Updating service
Successfully changed task definition to: scout-prod-td:18

Deploying new task definition...........................

Deployment failed
```

For what it's worth, I have two identical cluster (beta + staging) that run successfully with the same configurations.

Thanks!

**Comment by fabfuel** [comment]
Hi @jamesdixon, did you read this section already?
https://github.com/fabfuel/ecs-deploy#troubleshooting

Best
Fabian

**Comment by fabfuel** [comment]
Did you edit the output? Which version of `eco-deploy` do you use?

**Comment by jamesdixon** [comment]
@fabfuel we're running the latest version of ecs-deploy. I'm not sure what you mean by "did you edit the output?" Can you explain?

Yes, we're already using a timeout -- this is failing very quickly after the "Deploying new task definition" message appears.

Thank you!

**Comment by fabfuel** [comment]
Hi,

I meant, if this is the full output of the script or if you edited or removed something – because it looks unfamiliar.

Do you have any Event during the deployment in the `Events` tab of the service in the AWS ECS console?

Best
Fabian

**Comment by fabfuel** [comment]
"Very quickly" can't be, because every dot after "Deploying new task definition" means, it waiting for one second. This took at least 26 seconds until it failed. 

But what I'm missing is the error itself. Do you see this error message?
```
Deployment failed due to timeout. Please see: https://github.com/fabfuel/ecs-deploy#timeout
```
What command do you use for triggering the deployment?

**Comment by gadomsky** [comment]
@fabfuel 
We have similar situation, but in our case increasing timeout won't help, because we deploy image which is expected to fail (we have implemented health-checks in our containers - so the new task definition should fail end exit with non-zero status, and the previous one should live all the time). At this point, after failure new task definition should be deregistered - but is not.
What do you thing about new flag (eg. deregister-new-task-on-failure)?  
We could provide PR with such feature.

**Comment by jamesdixon** [comment]
@fabfuel thanks for the tip on the "Events" section. Missed that!

Turns out the instance didn't have enough memory given the memory limit on the container. 

Sorry for the false alarm!

**Comment by fabfuel** [comment]
Hi @gadomsky, have you tried the `--rollback` option?
