### ISSUE TITLE
Is it possible to deploy across multiple service in one deployment?

### ISSUE THREAD

**Issue by Rahul91** [fabfuel/ecs-deploy#98]
I have 2 services running in my cluster and during deployments, I need to update containers images of both the service, is it possible to do that with one deployment command?

**Comment by fabfuel** [comment]
Hi @Rahul91,

no, ecs-deploy always modifies one specific service at a time and monitors its deployment for success and I would like to keep it that way and delegate orchestration of multiple service deployments to an external task runnner.

Best
Fabian

**Comment by omaraltayyan** [comment]
@fabfuel  are there any negatives to running this process multiple times in the background and calling `wait` so that all services deploy at the same time?

**Comment by fabfuel** [comment]
I don't think so. This should work fine, as long as your cluster has enough overhead to deploy multiple services at the same time. This may lead to many more running containers for a short amount of time, depending on your ECS deployment configuration [min/max].

Best
Fabian
